### ISSUE TITLE
Tiller Deprecated

### ISSUE THREAD

**Issue by jasperf** [dambergautam/laravel-kubernetes-helm#3]
Tiller has been removed from Helm 3 https://helm.sh/blog/helm-3-preview-pt2/ (blog post Thu, Apr 25, 2019)

_With Tiller gone, the security model for Helm is radically simplified. Helm 3 now supports all the modern security, identity, and authorization features of modern Kubernetes. Helm's permissions are evaluated using your kubeconfig file. Cluster administrators can restrict user permissions at whatever granularity they see fit. Releases are still recorded in-cluster, and the rest of Helm's functionality remains._

So would be good to update `bin/publish_chart.sh` to reflect this as well.

See https://helm.sh/docs/helm/helm_upgrade/ upgrade options as they are in use now.

**Comment by dambergautam** [comment]
Thanks @jasperf for letting me know. I have updated script now.
